gwpy/pyomicron

- bin/omicron-process
- bin/omicron-status
- omicron/condor.py
- omicron/const.py
- omicron/io.py
- omicron/nagios.py
- omicron/segments.py
This PR introduces a number of improvements to `pyomicron` for online processing, including
- new `omicron-status` script for checking processing success, with ouputs to dashboard.ligo.org-format JSON
- updates for Omicron v2r2 developments (many thanks to @FlorentRobinet)
- associated bug fixes and reliability improvements
> Myriad improvements for online processing

- bin/omicron-status
This PR adds a few lines of JSON to print the versions of omicron and pyomicron.
> Added version info to JSON output

- omicron/utils.py
New version syntax v2r2p0 broke the version formatting, this PR fixes that. This is a bit of a hack of the syntax because v2r2p0 is _not_ the same version as v2r2.
Perhaps @FlorentRobinet could be convinced to use [Semantic Versioning](http://semver.org/) for omicron to remove the need for custom version parsing (this is handled by python system libraries).
> Updated version parsing to handle vXrYpZ format

- bin/omicron-status
This PR improves the check for 'unresolvable' segments; now only complete state segments that are shorter than the segment length will be marked as unresolvable. Everything else is a gap.
> Expanded unresolvable check

- .travis.yml
- bin/omicron-process
- omicron/condor.py
- omicron/tests/mock_classad.py
- omicron/tests/mock_htcondor.py
- omicron/tests/test_condor.py
- omicron/tests/utils.py
This PR improves the `omicron.condor` module by simplifying interactions with `htcondor.Schedd`. This PR also adds a test suite for that module.
> Condor module improvements

- bin/omicron-process
This PR modifies the way online segments are truncated to prevent the next iteration receiving a segment that is too small.
> Re-worked online segment selection for omicron-process

- omicron/data.py
This PR modies the `omicron.data` module to use the latest GWF file path returned by datafind and interpolate forward to find the actual most recent file available on disk.
This should reduce latency.
> Interpolate GWF file paths beyond datafind's knowledge

- omicron/segments.py
This PR adds frameCPP-specific optimisations for reading GWF data from LIGO 'raw' files, which greatly speeds things up and reduces memory.
> Added optimisations for frameCPP GWF reading

- bin/omicron-status
- omicron/condor.py
- omicron/io.py
- omicron/segments.py
This PR fixes one bug related to gwpy-0.8, and also promotes gwpy imports to module-level, since this package is installed on the LDG systems by default.
> Some updates to support gwpy>=0.8

- .gitignore
- .travis.yml
- omicron/condor.py
- omicron/parameters.py
- omicron/tests/test_parameters.py
- omicron/utils.py
- requirements.txt
- setup.cfg
- setup.py
This PR fixes some syntax as far as getting the test suite running under python3.
> Fixed some syntax for python3

- bin/omicron-status
- requirements.txt
- setup.py
This PR updates `omicron-status` to use `gwpy.plot` from gwpy >= 0.13.0.
> Update to gwpy.plot in omicron-status

- README.md
- omicron/condor.py
- omicron/data.py
- omicron/io.py
- omicron/log.py
- omicron/nagios.py
- omicron/parameters.py
- omicron/segments.py
- omicron/tests/mock_htcondor.py
- omicron/tests/test_condor.py
- omicron/tests/test_segments.py
- omicron/utils.py
- setup.cfg
This PR modifies `README.md` to show installation instructions, and configures `flake8` in `setup.cfg/[flake8]`. I then fixed all the flake8 issues.
> Added flake8 configuration and fixed exposed issues

- omicron/data.py
This PR patches `omicron.data` to augment an aggregated-h(t) cache (e.g. for `H1_HOFT_C00`) with short h(t) GWF files (e.g. `H1_DMT_C00`). This should help minimise the latency of trigger production for LIGO on h(t).
> Augment aggregated h(t) with short frames

- .travis.yml
- azure-pipelines.yml
- environment.yml
This PR represents a first cut at migrating from TravisCI to Azure Pipelines, which as better cross-platform support, and natively supports both conda.
> WIP: Attempt at azure pipelines configuration

- .pep8speaks.yml
- .travis.yml
- bin/omicron-process
- bin/omicron-root-merge
- bin/omicron-status
- omicron/const.py
- omicron/segments.py
- omicron/tests/test_nagios.py
- omicron/tests/test_utils.py
- setup.cfg
- setup.py
This PR enables the `flake8` linter in CI, then fixes all of the issues it exposes.
> Enable flake8 linting and correct issues

- .travis.yml
- bin/omicron-print
This PR fixes a bug in `omicron-print` introduced by #96.
> Fix bug in omicron-print

- omicron/segments.py
This PR adds support for analysing KAGRA lock data.
> Add KAGRA lock information

- requirements.txt
- requirements.yml
This PR updates version pins for a few package dependencies based on experience with LIGO's production omicron environments.
> Update package dependence version pins

- omicron/tests/test_condor.py
This PR fixes a flake8 issue that appears in the latest version that didn't used to appear.
> Fix noqa for updated flake8

- omicron/tests/test_utils.py
This PR fixes the test failure seen during conda build testing.
> Fix test patch on py36

- .readthedocs.yml
- docs/environment.yml
This PR adds a readthedocs configuration file.
> Add readthedocs configuration

- README.md
- docs/index.rst
- omicron/io.py
This PR updates a number of URLs to other projects, and the installation instructions.
> Update documentation links in various places

- RELEASE.md
> Minor updates to release procedure docs

- omicron/tests/test_segments.py
- setup.cfg
remove an unused line in setup.cfg
> change a test function name because of a [spurious] error in conda-forge

- .github/workflows/build.yml
- setup.cfg
This PR updates the classifiers and CI to add support for Python 3.11.
> Add support for Python 3.11

- omicron/segments.py
- setup.cfg
> correctly import default segment host
