- bin/omicron-process
- omicron/data.py
- omicron/segments.py
This PR introduces support for reading GWF files from the `/dev/shm` shared-memory buffer used in LIGO for low-latency frames.
The biggest possible problem is that these frames may disappear from the buffer before omicron gets a chance to read them, so my solution uses a temporary cache under `/tmp` that is cleaned up when the DAG is complete.
Fixes #2.
> Added support for reading frames from /dev/shm

- .travis.yml
- bin/omicron-process
- omicron/const.py
- omicron/io.py
- omicron/tests/test_io.py
- requirements.txt
This PR fixes #5 by removing the epoch name from the directory-naming convention for the trigger archive.
This is mainly achieved by introducing a new method `omicron.io.get_archive_filename` which builds the filename for a given channel, and GPS segment, which is used in `omicron-process` to name the coalesced XML and ROOT files.
> Removed epoch directory from archive convention

- bin/omicron-root-merge
- omicron/io.py
This PR fixes #8 by removing the options to preserve only the metadata from the first ROOT file from `omicron.io.merge_root_files` and the `omicron-root-merge` executable.
> Preserve all metadata when merging ROOT files

- bin/omicron-print
- omicron/io.py
This PR introduces `omicron-print`, a command-line executable for printing file locations (similar to `gw_data_find` from `glue`) or the events themselves.
> New omicron-print executable

- bin/omicron-status
This PR fixes a bug in `omicron-status` that would raise a `ValueError` when trying to unzip an empty state segment list.
> Fixed ValueError in omicron-status when no state segments

- omicron/parameters.py
This PR sets the default `FFTPLAN` parameter for Omicron v2r2 as `FFTW_ESTIMATE`. @FlorentRobinet has advised this to be better for processing small numbers of chunks, so you spend more time running FFTs, but less this working out a plan at the beginning.
This isn't exposed to the user in a useful way just yet.
> Set default FFTPLAN as FFTW_ESTIMATE for Omicron v2r2

- bin/omicron-status
This PR modifies `omicron-status` to show the nagios notification thresholds on the latency axes.
> Show notification thresholds on omicron-status latency plot

- omicron/condor.py
This PR adds a catch for errors of the format:
```python
RuntimeError: Cowardly refusing to queue more than 1000 requests.
```
coming from a `Schedd.history` call.
> Catch 'cowardly refusing' errors and retry via shell

- bin/omicron-status
This PR fixed two problems with the `condor-status` executable
- need to make the output directory if it doesn't exist
- need to include `USER` name in all condor queries, otherwise `detchar` will clash against the personal user of anyone doing any testing
> Include USER in all condor queries

- bin/omicron-process
This PR fixes #20 by setting `cachesegs = Cache()` if no frames are found for the data interval.
> Fixed NameError in omicron-process if all frames missing

- bin/omicron-process
This PR adds a new `-x/--exclude-channel` command-line option to removed one or more channels from the analysis without having to edit the config file.
> Added --exclude-channels option to omicron-process

- bin/omicron-process
- bin/omicron-status
This PR modifies `omicron-process` to _always_ write the `segments.txt` file, even in the analysis fails. This means that an online analysis will _always_ move on to the next segment, and won't get hung up on one broken chunk.
> Always write segments.txt file

- bin/omicron-process
This PR fixes a problem whereby a `glue.segments.segmentlist` slices to a simple `list`- just need to type-case back again.
> Fixed TypeError in using segmentlists

- .travis.yml
- bin/omicron-status
This PR adds verbose logging to the `omicron-status` utility, mainly for debugging purposes.
Also, I added a new `-C/--skip-job-duration` command-line option to skip querying the condor history for job durations, which takes forever.
> Added verbosity to omicron-status

- bin/omicron-status
This PR modifies `omicron-status` to check frame availability even when there is a state flag, so that we don't flag missing data as a gap in the archive.
> Check frame availability with state in omicron-status

- bin/omicron-process
- omicron/condor.py
This PR introduces the `--reattach` command-line option for `omicron-process`, allowing the processor to skip submitting a new DAG and just watch an already running DAG, if and only if a `dag.lock` file is found where expected. If no lock file is found, things proceed as normal.
> Added --reattach option to omicron-process

- bin/omicron-status
This PR adds the ability for `omicron-status` to skip over gaps that have been 'acknowledged', via segments written into a file `acknowledge-gaps-<tag>.txt`. This is useful for gaps that can't be removed, so that nagios will re-notify on new (unacknowledged) gaps.
> Allow gaps to be 'acknowledged' in omicron-status

- bin/omicron-process
This PR modifies the check that 'all data' are available. This check is used to record that a certain chunk of time has been checked for state segments, and that none were found, but currently fails when there is a missing frame. This means that during extended periods of no operations, the segment to be checked grows continuously.
The check is now that the most recent available data file is up-to-date. This will in general mean that more gaps are created, but those can be filled in after-the-fact.
> Ignore missing frames when determining 'all data'

- omicron/data.py
This PR modifies the `ligo_low_latency_hoft_type` function to use the new `{IFO}_DMT_C00` frametype for the 4-second frames produced by LIGO.
> Updated llhoft frametype to {IFO}_DMT_C00 type

- bin/omicron-process
This PR fixes an `IndexError` when the returned cache of data files doesn't actually overlap the span of times asked for.
> Handle no frame files in omicron-process

- bin/omicron-process
- omicron/condor.py
This PR introduces a more robust way of testing whether a DAG has already been submitted for a given channel group. It's not quite enough just to test for a `dag.lock` file, mainly if condor hasn't actually started the scheduler `condor_dagman` job yet.
> Improved check whether DAG is already running

- bin/omicron-process
- omicron/condor.py
This PR modifies the `omicron-process` script to wait until the dagman process is in the 'running' state before attempting to watch it.
Also, fixed some bugs introduced by #35.
> Wait until DAGMan is running before watching

- omicron/segments.py
This PR modifies the `segments.get_state_segments` method to round (in general) non-integer state segments read from frames to have integer boundaries. This is done by contracting the segment inwards to the integer boundaries to match the DMT `SegGener` configuration.
> Round state segments inwards to integers

- bin/omicron-process
- bin/omicron-status
- omicron/segments.py
This PR adds a new configuration option
```ini
state-padding = start, end
```
that can be used to contract state segments at either end, default is `0,0`. This might be useful for channels/groups that will go bananas when lock is lost.
> Added option to pad state segments

- bin/omicron-status
This PR adds two new command-line options to `omicron-status`:
- `--state-flag`, to specify the state for a group, instead of taking it from the configuration file
- `--state-pad`, to add a custom padding when specifying `--state-flag`
The default behaviour of `omicron-status` is unchanged.
> Added --state{flag,pad} omicron-status options

- bin/omicron-process
This PR adds a new command-line option `--no-segdb` to `omicron-process`, forcing state segments to be determined from the frames, rather than querying the segment database - this is useful under service outages of DQSEGDB, for example.
> Added --no-segdb option to omicron-process

- bin/omicron-process
- omicron/condor.py
This PR modifies `omicron-process` to only write the `segments.txt` file if the workflow DAG gets submitted successfully. This means the processing will repeat if the DAG doesn't get submitted, which is good, but not if the DAG gets submitted and fails.
> Write segments.txt after workflow is submitted

- bin/omicron-process
This PR modifies the post-processing state of `omicron-process` to combine `omicron-root-merge` and `ligolw_add` operations into groups, thereby reducing the number of tiny nodes in the workflow, and so speeding things up a bit.
This should reduce the overhead on condor for assigning and matching large numbers of tiny nodes.
> Combine post-processing operations into groups

- bin/omicron-status
This PR modifies `omicron-status` to prints gaps, overlaps, and latency information to the JSON files in their own section, for machine readability.
> Improved JSON output for omicron-status

- omicron/data.py
This PR fixes two small issues with using llhoft (low-latency h(t)) frames at CIT
- [0356b80] only match LIGO h(t) frames as using `/dev/shm`
- [9ee338b] don't read most recent llhoft frame, which may still be being written when it gets read (causing corruption problems)
> Fixed two bugs in using llhoft frames at CIT

- omicron/segments.py
This PR adds state-vector mappings for the Virgo locked and science flags.
> Added Virgo flag mapping for ITF_LOCKED and ITF_SCIENCE

- bin/omicron-process
- docs/workflow/index.rst
This PR fixes #53 by adding a new command line option to pass a custom LAL-format cache file to `omicron-process`.
> Added --cache-file option to omicron-process

- omicron/data.py
This PR fixes an `IndexError` that occurs when no frames are returned by `datafind.find_frame_urls`.
> Fixed IndexError for no frames in data.find_frames

- omicron/segments.py
This PR moves the frameCPP import (used to determine only whether it is present, and isn't actually used) into the method where it is used. This works around a segfault in `LDAStools.frameCPP` somewhere.
> Moved frameCPP import into function

- bin/omicron-status
This PR changes the file extension for the `nagios-latency-%(group)` file stored as part of `omicron-status`. `.h5` is a little more standard than `.hdf`.
> Use h5 for file extension in omicron-status

- bin/omicron-process
- omicron/data.py
- omicron/segments.py
This PR improves the handling of the `--use-dev-shm` option for `omicron-process` and subsequent access to files under `/dev/shm` on the LIGO computing system.
> Improved data access for shared-memory files

- omicron/const.py
- omicron/data.py
- omicron/segments.py
- requirements.txt
- setup.py
> Update glue dependence to 1.60.0, require ligo-segments

- bin/omicron-process
- requirements.txt
- setup.py
This PR updates `omicron-process` to use the `--ilwdchar-compat` flag for `ligolw_add` as provided by `python-ligo-lw`.
> Use ligolw_add from python-ligo-lw

- .travis.yml
- bin/omicron-hdf5-merge
- bin/omicron-process
- omicron/io.py
- omicron/parameters.py
- requirements.txt
- setup.py
This PR adds support for the HDF5 format written by `Omicron`, as follows:
- added `omicron-hdf5-merge` script to merge H5 files
- added HDF5 output as default `OUTPUT FORMAT` for omicron-v2r3
- added support for merging HDF5 as part of the workflow
> Added support for handling HDF5 files created by Omicron.exe

- bin/omicron-print
- bin/omicron-process
- bin/omicron-status
- omicron/data.py
- omicron/io.py
- omicron/nagios.py
- omicron/segments.py
- requirements.txt
- setup.py
This PR updates `pyomicron` to use `gwdatafind` for GWF discovery.
This API returns simple file paths, so included are modifications to everything needed to just use these paths` rather than the `glue.lal.Cache` or `lal.utils.CacheEntry` objects.
I also updated `omicron-print` to support modern versions of `gwpy`, and HDF5.
> Upgrade to gwdatafind for GWF discovery

- omicron/io.py
This PR updates `omicron.io` to support old versions of `h5py` where `AttributeManager` doesn't have the `update()` method.
> Support old h5py

- omicron/segments.py
- requirements.txt
- setup.py
This PR updates `omicron.segments` to use the `dqsegdb2` library to query a LIGO-Virgo segment database for flag information. This library is much lighter than `dqsegdb`, and works on python3.
> Use dqsegdb2 for getting flag availability

- omicron/segments.py
This PR updates `omicron.segments` to read the default DQSEGDB hostname from the `DEFAULT_SEGMENT_SERVER` environment variable, rather than hardcoding `https://segments.ligo.org` in multiple places.
> Use DEFAULT_SEGMENT_SERVER to get default segments location

- .travis.yml
- omicron/tests/__init__.py
- omicron/tests/mock_htcondor.py
- omicron/tests/test_condor.py
- omicron/tests/test_io.py
- omicron/tests/test_log.py
- omicron/tests/test_nagios.py
- omicron/tests/test_parameters.py
- omicron/tests/test_utils.py
- requirements.txt
- setup.cfg
This PR modifies the `omicron.tests` test suite to use `pytest` for all testing syntax, rather than `unittest`.
> Move to pytest for all syntax

- omicron/segments.py
This PR updates the use of `glue.segmentsUtils` to `ligo.segments.utils`.
> Fixed import of segmentsUtils

- omicron/segments.py
This PR fixes a serious typo in discovery of `frameCPP` and subsequent setting of keyword arguments for `StateVector.read` in `omicron.segments`.
> Fixed frameCPP keyword arguments for reading state-vector

- bin/omicron-process
- omicron/segments.py
- omicron/tests/test_segments.py
- requirements.txt
- setup.py
This PR adds a `omicron.segments.get_guardian_segments` function that checks `*_STATE_N == *_NOMINAL_N & *_ACTIVE == 1` for the given guardian node, as required for guardian use in O3 for LIGO.
> Added support for parsing segments from guardian states

- bin/omicron-status
This PR adds `.h5` file availability to the plots produced by `omicron-status`, and also adds the 'raw' availability (not filtered by segments).
> Added HDF5 to omicron-status plots

- bin/omicron-print
This PR updates `omicron-print` to run on python3, mainly by refactoring to use gwpy's filter parser, rather than using a homebrewed version.
> Updated omicron-print for python3

- bin/omicron-status
- omicron/segments.py
- requirements.txt
- setup.py
This PR removes a couple of references to glue, such that the only remaining requirement is `glue.pipeline`, which doesn't require lalsuite (which is nice).
> Updated references to lscsoft-glue

- omicron/segments.py
- requirements.txt
- setup.py
This PR adds `omicron.segments.data_segments()` which determines those segments that could yield data, without parsing the data themselves. This is mainly to overcome the problems at Virgo whereby the state vector channel isn't guaranteed to be in the frames at all.
> Added data_segments function to parse available data segments from GWF

- bin/omicron-process
- omicron/io.py
- omicron/parameters.py
- omicron/segments.py
This PR fixes some python3 issues, mainly using r-strings for regular expressions, and casting `map()` to `list`.
> Fixed a few python3 compatibility issues

- omicron/const.py
- omicron/tests/test_condor.py
- omicron/tests/test_const.py
- omicron/tests/test_parameters.py
- omicron/tests/test_segments.py
- omicron/tests/utils.py
This PR updates `omicron.const` to use regular expressions to match the FQDN of the host to an IFO prefix.
I also added a regex for KAGRA (`'K1'`), and some unit tests.
> Use FQDN regular expression to set default IFO

- bin/omicron-process
- bin/omicron-status
- omicron/segments.py
This PR fixes some failures on python3 where `map()` was not cast to `tuple` or `list` before being indexed.
> Cast map() to tuple or list where necessary

- omicron/segments.py
This PR patches `omicron.segments` to use `V1Online` as the default frametype for Virgo state data, the new `AGGREGATED_HOFT` stuff (#93) should mean this works just fine.
> Use V1Online for Virgo state

- bin/omicron-process
This PR fixes a bug in `omicron-process` where the `segments.txt` was being moved, not copied.
> Fixed bug in archiving segments.txt file

- omicron/condor.py
- omicron/tests/test_condor.py
This PR simplifies the `dag_is_running` function to just check for existence of the `.dag.lock` file.
> Simplified omicron.condor.dag_is_running function

- bin/omicron-process
This PR works around a failure in `omicron-process` when `omicron.condor.get_dag_status` can't evaluate the `exitcode` of the given DAG.
> Handle missing exitcode from get_dag_status in omicron-process

- bin/omicron-process
This PR fixes the logic for the `--rescue option` in `omicron-process` (which has been broken forever), and moved the definition of `"omicron.dag"` to a variable that sits at the top of the script.
> Removed repetition of 'omicron.dag' and fixed --rescue option for omicron-process

- bin/omicron-print
- bin/omicron-process
This PR removes all `from __future__` imports; since we require python>=3.6, we don't need them.
> Removed unnecessary __future__ imports

- bin/omicron-process
- omicron/condor.py
- omicron/tests/test_utils.py
- omicron/utils.py
- setup.py
This PR implements a few things in order to use a custom, temporary directory for the astropy configuration files. This should hopefully mitigate the sort of issues that @alurban and I have seen when running in production for LIGO.
Summary of changes:
- new `omicron.utils.astropy_config_path` function to create temporary `XDG_CONFIG_HOME`,
- `omicron.condor.submit_dag` now passes `os.environ` to the subprocess,
- `omicron-process` calls `astropy_config_path` to build a custom, temporary astropy configuration path, deleting after the workflow completes (successfully).
> Use custom astropy config directory for omicron-process workflows

- bin/omicron-status
This PR patches `omicron-status` to handle `OSErrors` raised when reading the HDF5 latency archive file. The latency data is only used to make the plot, so we shouldn't really be critically failing if we can't read it, so just catch the exceptions from HDF5 and let's move on with our lives.
This is hot-fixed in production at LLO as a test.
> Handle OSErrors from reading h5 in omicron-status

- .travis.yml
This PR removes the caching of conda packages in the travis builds, it seems to just slow things down. ATOW this is `WIP` since I'm not sure my statement is actually true.
> Remove conda cache in travis

- .travis.yml
- setup.py
This PR adds a travis job for python3.8, and the equivalent PyPI classifier declaring python3.8 support.
> Add support for python3.8

- omicron/segments.py
This PR implements explicit support for GEO600 science and lock segments, so that production Omicron analyses can be run on G1 data.
cc @duncanmmacleod
> Support GEO600 science segments

- bin/omicron-process
- omicron/const.py
- omicron/parameters.py
- omicron/tests/test_parameters.py
- omicron/tests/test_utils.py
- omicron/utils.py
- requirements.yml
- setup.py
This PR upgrades the `omicron` requirement to 2.3.12 (the first conda-compatible release) and removes support for all older versions, allowing for a cleanup of some legacy-support code.
The following was tested on the LDAS computing center at Caltech to verify:
```shell
omicron-process GW -f ~detchar/omicron/online/l1-channels.ini --gps 1262995218 $((1262995218+600)) --ifo L1 --output-dir ~/tmp/pyomicron-test2 -v --condor-accounting-group ligo.dev.o3.detchar.transient.omicron --archive --condor-command "request_memory=4096" -v
```
> Migrate omicron support to >=2.3.12

- .travis.yml
This PR addresses an issue in the CI where the desired python version is completely ignored and all jobs use the latest version.
> Install the correct python version up front in CI

- omicron/cli/status.py
- omicron/const.py
Old issue about poor error message when we can not determine defaults for IFO and omicron configuration file.
We do not need to create a new release right away for such a small fix
> Address issue #43, bad error message(s) for missing arguments

- docs/index.rst
- docs/workflow/simulations.rst
- omicron/cli/merge_with_gaps.py
- omicron/cli/process.py
This addresses issue https://github.com/gwpy/pyomicron/issues/144 by not creating trigger files that cross a metric day boundary (100,000 seconds).
The problem is that searches for triggers (gwtrigfind like) are based in the metic day directory structure so if an analysis segment starts in one day and crosses into the next a search would not see triggers in the next but our overlap checks spot them.
There was also a snippet from PR #143 that did not make into that PR by mistake.
We found this one filling PEM gaps that ended up with one trigger file covering 68 hrs.
> Merge day boundary

- omicron/data.py
This PR updates the low-latency frame-finding logic to look in `/dev/shm/kafka`, rather than `/dev/shm{/llhoft}`.
This should resolve the current issue that Virgo data are apparently not discoverable at CIT [[ref](https://dashboard2.ligo.uwm.edu/icingaweb2/icingadb/service?name=omicron-online-GW&host.name=detchar-cit#!/icingaweb2/icingadb/comment?name=detchar-cit%21omicron-online-GW%219fc0f671-9952-4526-bf2c-6dc4642f4048)].
> Update find_ll_frames to look in /dev/shm/kafka

- omicron/cli/status.py
This PR improves the formatting of `SegmentList` objects in nagios JSON reports generated by `omicron-status`.
The problem is, e.g. [here](https://ldas-jobs.ligo-la.caltech.edu/~detchar/omicron/nagios/PEM2/nagios-gaps-PEM2.json)), that standard representation of a `gwpy.segment.SegmentList` includes angle brackets (`<` and `>`) which the HTML renderer on dashboard.igwn.org can't handle, so the segment information is just lost.
The fix here is a more brute-force detailed formatting of the segments.
> Improve formatting of segments for nagios from omicron-status

- omicron/cli/process.py
This PR fixes a trivial typo in a log message from `omicron-process` (it confused me for a few minutes).
> Fix typo in log omicron-process message

- .github/workflows/build.yml
This PR makes a tweak to the CI configuration to install `pip2conda` into its own environment, which allows using a newer version of Python than in the `base` environment.
> Install pip2conda in its own environment in CI

- omicron/tests/mock_htcondor.py
This PR removes an unused variable from the `mock_htcondor` module that was failing the lint check.
> Remove unused variable

- omicron/cli/process.py
This PR removes the `use_x509userproxy` command from all HTCondor workflows, none of the jobs need it.
This also sets a global default `request_memory` for all jobs to 1024, which isn't actually a change, but refactors slightly _where_ the default is set.
> Don't attempt to pass X.509 credentials to jobs

- omicron/utils.py
This PR patches `omicron.utils.get_omicron_version()` to always set `OMICRON_HTML` (to [`gettempdir()`](https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir)) to avoid [a segfault](https://git.ligo.org/virgo/virgoapp/Omicron/-/issues/81).
> Set OMICRON_HTML in omicron.utils.get_omicron_version
